{
 "title": "Speed & Temperature",
 "tags": [ "TeslamateCustomDashboards" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT\n    id as __value,\n    CASE WHEN COUNT(id) OVER (PARTITION BY name) > 1 AND name IS NOT NULL THEN CONCAT(name, ' - ', RIGHT(vin, 6)) ELSE COALESCE(name, CONCAT('VIN ', vin)) end as __text \nFROM cars\nORDER BY display_priority ASC, name ASC, vin ASC"
   },
   {
    "name": "current_capacity",
    "query": "WITH Aux AS\n(SELECT car_id,\n\t\tCOALESCE(efficiency, \n\t\t(SELECT efficiency\n\t\t\tFROM cars WHERE id = $car_id) * 100) AS efficiency\n\tFROM (\n\t\tSELECT ROUND((charge_energy_added / NULLIF(end_rated_range_km - start_rated_range_km, 0))::numeric, 3) * 100 as efficiency,\n\t\t\tCOUNT(*) as count, $car_id AS car_id \n\t\tFROM charging_processes\n\t\tWHERE car_id = $car_id\n\t\t\tAND duration_min > 10\n\t\t\tAND end_battery_level <= 95\n\t\t\tAND start_rated_range_km IS NOT NULL\n\t\t\tAND end_rated_range_km IS NOT NULL\n\t\t\tAND charge_energy_added > 0\n\t\tGROUP BY 1\n\t\tORDER BY 2 DESC\n\t\tLIMIT 1\n\t) AS DerivatedEfficiency\n),\nCurrentCapacity\t AS\n(\n\tSELECT AVG(Capacity) AS Capacity\nFROM (\nSELECT \n\tc.rated_battery_range_km * aux.efficiency / c.usable_battery_level AS Capacity\n\tFROM charging_processes cp\n\t\tINNER JOIN charges c\n\t\tON c.charging_process_id = cp.id \n                INNER JOIN aux ON cp.car_id = aux.car_id\n\tWHERE cp.car_id = $car_id\n\t\tAND cp.end_date IS NOT NULL\n\t\tAND cp.charge_energy_added >= aux.efficiency\n\t\tAND c.usable_battery_level > 0\n\t ORDER BY cp.end_date DESC LIMIT 10) AS lastCharges\n)\nSELECT Capacity FROM CurrentCapacity"
   },
   {
    "name": "datapoints",
    "label": "Used datapoints",
    "query": "100% : 100, 50% : 50, 20% : 20, 10% : 10"
   },
   { "name": "speed_step", "label": "Speed step", "query": "20, 10, 5" },
   { "name": "temperature_step", "label": "Temperature step", "query": "10, 5, 2.5" },
   {
    "name": "length_unit",
    "query": "SELECT unit_of_length FROM settings LIMIT 1"
   },
   {
    "name": "temp_unit",
    "query": "select unit_of_temperature FROM settings LIMIT 1"
   },
   {
    "name": "base_url",
    "query": "SELECT base_url FROM settings LIMIT 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Data Query",
   "type": "table",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH SpeedData AS (\n  SELECT \n    speed,\n    temperature,\n    COUNT(*) as samples,\n    ROUND(AVG((power / speed) * 1000), 1) AS consumption\n  FROM (\n    SELECT \n      ROUND(convert_km(speed::numeric, '$length_unit') / ($speed_step * 1.0)) * $speed_step AS speed,\n      TO_CHAR(ROUND(AVG(convert_celsius(outside_temp, '$temp_unit') / ($temperature_step * 1.0)) OVER(ORDER BY date ROWS BETWEEN 50 PRECEDING AND 50 FOLLOWING)) * $temperature_step, 'FM999') AS temperature,\n      power\n    FROM positions \n    WHERE $__timeFilter(date) AND car_id = $car_id AND speed > 0 AND (id % (100 / $datapoints)::integer = 0 OR outside_temp IS NOT NULL)\n  ) AS RawData\n  WHERE temperature IS NOT NULL AND speed > 0 \n  GROUP BY temperature, speed\n)\nSELECT\n  speed, temperature,\n  consumption, \n  (1000 * $current_capacity / consumption) AS range,\n  ROUND(100 * (samples * speed) / (SELECT SUM(speed * samples) FROM SpeedData), 3) AS distance_percentage,\n  ROUND((samples * speed) / (SELECT SUM(speed * samples) FROM SpeedData AS SampleData WHERE SampleData.temperature = SpeedData.temperature), 3) AS at_temperature_percentage,\n  ROUND((samples * speed) / (SELECT SUM(speed * samples) FROM SpeedData AS SampleData WHERE SampleData.speed = SpeedData.speed), 3) AS at_speed_percentage\nFROM SpeedData \nWHERE consumption > 0 AND speed > 0 AND samples > (200*($datapoints/100.0)) \nORDER BY speed, temperature::numeric"
    }
   ]
  },
  { "title": "Speed & Temperature Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Consumption (Wh/$length_unit) by Speed & Temperature",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 2 },
   "targets": [
    { "panelId": 25 }
   ]
  },
  {
   "title": "Range ($length_unit) by Speed & Temperature",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "panelId": 25 }
   ]
  },
  {
   "title": "Consumption by Temperature (º$temp_unit)",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 19 },
   "targets": [
    { "panelId": 25 }
   ]
  },
  {
   "title": "Consumption by Speed ($length_unit/h)",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 19 },
   "targets": [
    { "panelId": 25 }
   ]
  },
  {
   "title": "Range ($length_unit) by Temperature (º$temp_unit)",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 6, "x": 12, "y": 19 },
   "targets": [
    { "panelId": 25 }
   ]
  },
  {
   "title": "Range ($length_unit) by Speed ($length_unit/h)",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 19 },
   "targets": [
    { "panelId": 25 }
   ]
  },
  { "title": "Distance Related Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Driven Distance Percentage by Speed & Temperature",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 25 }
   ]
  },
  {
   "title": "Driven Distance ($length_unit) by Temperature (º$temp_unit)",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 6, "x": 12, "y": 35 },
   "targets": [
    { "panelId": 25 }
   ]
  },
  {
   "title": "Driven Distance by Speed ($length_unit/h)",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "panelId": 25 }
   ]
  },
  { "title": "Other Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Short & Long Trips Consumption by Temperature",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "SELECT \n  convert_celsius(temperature, '$temp_unit') AS temperature, AVG(consumption) AS consumption\nFROM (\n  SELECT \n    ROUND(outside_temp_avg/($temperature_step*1.0)) * $temperature_step AS temperature, \n    (NULLIF(GREATEST(start_rated_range_km - end_rated_range_km, 0), 0) * cars.efficiency * (1000 / convert_km(distance::numeric, '$length_unit'))) AS consumption\n  FROM \n    drives JOIN cars ON drives.car_id = cars.id WHERE drives.car_id = $car_id AND convert_km(distance::numeric, '$length_unit') BETWEEN 1 AND 20\n) S1 GROUP BY temperature ORDER BY temperature ASC\n"
    },
    {
     "rawSql": "SELECT \n  convert_celsius(temperature, '$temp_unit') AS longtemp, AVG(consumption) AS longconsumption\nfrom (\n  SELECT \n    ROUND(outside_temp_avg/($temperature_step*1.0)) * $temperature_step AS temperature, \n    (NULLIF(GREATEST(start_rated_range_km - end_rated_range_km, 0), 0)*cars.efficiency * (1000 / convert_km(distance::numeric, '$length_unit'))) AS consumption\n  FROM \n    drives JOIN cars ON drives.car_id = cars.id WHERE drives.car_id = $car_id AND convert_km(distance::numeric, '$length_unit') > 20 \n) S1 GROUP BY temperature ORDER BY temperature ASC"
    }
   ]
  },
  {
   "title": "Consumption & Temperature by Date",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "rawSql": "SELECT \n  start_date::date AS time,\n  consumption/(convert_km(distance::numeric, '$length_unit')/100) AS consumption\nFROM (\n  SELECT \n    start_date,\n    SUM(distance*consumption/100) OVER(ORDER BY start_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS consumption,\n    SUM(distance) OVER(ORDER BY start_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS distance\n  FROM (\n    SELECT \n      start_date, SUM(distance) AS distance, \n      SUM(distance*consumption)/SUM(distance) AS consumption\n    FROM (\n      SELECT \n        TO_CHAR(start_date, 'YYYY-MM-DD') AS start_date,\n        (end_km-start_km) AS distance,\n        (NULLIF(GREATEST(start_rated_range_km - end_rated_range_km, 0), 0)*cars.efficiency * (1000/distance)) AS consumption\n      FROM \n        drives JOIN cars ON drives.car_id = cars.id  WHERE drives.car_id = $car_id\n    ) S1 WHERE consumption > 0 GROUP BY start_date ORDER BY start_date ASC\n  ) S2 GROUP BY start_date, distance, consumption ORDER BY start_date\n) S3 ORDER BY start_date\n          "
    },
    {
     "rawSql": "SELECT \n  start_date::date as time,\n  ROUND(convert_celsius(temperature, '$temp_unit')) AS temperature_$temp_unit\nFROM (\n  SELECT \n    start_date,\n    AVG(temperature) OVER(ORDER BY start_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS temperature\n  FROM (\n    SELECT \n      start_date, avg(temperature) as temperature\n    FROM \n      (\n        SELECT \n          to_char(start_date, 'YYYY-MM-DD') as start_date,\n          --(end_km-start_km) as distance,\n          outside_temp_avg as temperature\n        FROM \n          drives join cars on drives.car_id = cars.id  where drives.car_id = $car_id\n      ) S1 group by start_date order by start_date asc\n  ) S2 group by start_date, temperature order by start_date\n) S3 order by start_date"
    }
   ]
  }
 ]
}